### ISSUE TITLE
The call of a non-existing function

### ISSUE THREAD

**Issue by zergon321** [jpbouza/BlenRig#10]
Hi. I was going through the 51st step of the reproportion guide

![image](https://github.com/jpbouza/BlenRig/assets/22347549/65b5156a-681b-4b27-a2dc-d3badeb955bc)

I pushed the "Bake all" button, but I only got the error

```plaintext
Python: Traceback (most recent call last):
  File "C:\Users\maxim.LAPTOP-871B05H0\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenRig-6_v4_0_0\ops_baking.py", line 484, in execute
    self.bake_all_1(context)
  File "C:\Users\maxim.LAPTOP-871B05H0\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenRig-6_v4_0_0\ops_baking.py", line 479, in bake_all_1
    bpy.ops.armature.collection_solo_visibility(name="BONE-ROLLS")
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Calling operator "bpy.ops.armature.collection_solo_visibility" error, could not be found
```
I used BlenRig 6 v4.0.0 with Blender 4.1.1

**Comment by ChuChuCharlie** [comment]
Same error when using 4.1.1, works fine on the same file in 4.0

EDIT** The function bpy.ops.armature.collection_solo_visibility was removed between 4.0 and 4.1 https://projects.blender.org/blender/blender/commit/f623c8f7bc5847a771b86e6ba134a0ca704e480b

**Comment by danielanywhere** [comment]
I had the same error in Guide 1 - Reproportion Guide / 51 - Bake Rig / Bake All, and as @ChuChuCharlie indicated, I uninstalled Blender 4.1, reinstalled Blender 4.0, and retried the process. Baking the rig also worked fine on my model after that.

**Comment by cl3m3c7** [comment]
@zergon321 and @danielanywhere here is the fix if you are still interested:

1. go the the plugin's (BlendRig) folder
1. open `ops_baking.py` file
2. change the line `479` from `bpy.ops.armature.collection_solo_visibility(name="BONE-ROLLS")` to `context.object.data.collections_all["BONE-ROLLS"].is_solo = True`
3. change the line `506` from `bpy.ops.armature.collection_solo_visibility(name="REPROPORTION")` to `context.object.data.collections_all["REPROPORTION"].is_solo = True`

hope this helps!
