### ISSUE TITLE
BlenRig not working with the upcoming  blender 4.0!

### ISSUE THREAD

**Issue by cl3m3c7** [jpbouza/BlenRig#6]
Hi,
when I install the plugin and try to enable it, I get the following error:

```python
Traceback (most recent call last):
  File "C:\Users\User\Documents\blender-beta\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Users\User\Documents\blender-beta\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenRig-6_v2_1_0\__init__.py", line 78, in <module>
    from .ui.panels.guide_reproportion_assistant import BLENRIG_PT_reproportion_guide
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenRig-6_v2_1_0\ui\panels\guide_reproportion_assistant.py", line 2, in <module>
    from ...guides.guide_ops import VIEW3D_OT_blenrig_guide_reproportion
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenRig-6_v2_1_0\guides\guide_ops.py", line 8, in <module>
    from . draw import draw_callback_px
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenRig-6_v2_1_0\guides\draw.py", line 7, in <module>
    from . rectangle import Draw_Rectangle
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenRig-6_v2_1_0\guides\rectangle.py", line 6, in <module>
    shader = gpu.shader.from_builtin('2D_UNIFORM_COLOR')
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '2D_UNIFORM_COLOR'
```
any plans to update it to work with the new version?
thank you!

**Comment by jpbouza** [comment]
Hi! Yes, it doesn't work in 4.0. We just need to find the time to fix that. :)

**Comment by cl3m3c7** [comment]
I see, Thank you for your work :)
